// Get the modal and close button elements
var modal = document.getElementById("jobModal");
var closeModalBtn = document.getElementById("closeModalBtn");
var modalTitle = document.getElementById("modalTitle");
var modalContent = document.getElementById("modalDescription");

// Event listener for Close button
closeJobModal.addEventListener("click", function() {
    closeModal();
});

// Function to open the job modal with dynamic content
function openJobModal(jobTitle) {
    modal.style.display = "block";
    modalTitle.textContent = jobTitle;

    // Define job descriptions and qualifications (customize as needed)
    var jobDescriptions = {
        'Catering Manager': 'A Catering Manager is a professional who is responsible for monitoring the quality of food and service at their outlets. They ensure that all operations run smoothly, from cooking to serving customers, in order to achieve peak performance every day.',
        'Florist': 'A florist is a skilled professional responsible for creating and arranging floral designs, bouquets, and decorative flower arrangements. Florists work in various settings, including flower shops, floral studios, event planning companies, and garden centers. They use their artistic and botanical expertise to craft beautiful and visually appealing floral displays.',
        'Marketing Staff': 'Marketing staff members are crucial to the success of a companys marketing efforts. They play a key role in implementing marketing strategies, campaigns, and activities designed to promote products, services, or the overall brand. Marketing staff work closely with marketing managers and teams to achieve marketing objectives.',
        'Cook': 'A cook is responsible for preparing, cooking, and presenting a wide variety of dishes in a professional kitchen setting. Whether working in a restaurant, hotel, catering service, or other food service establishment, a cook plays a crucial role in delivering high-quality meals to customers.',
        'Assistant Cook': 'An assistant cook, often referred to as a line cook or prep cook, is an essential member of a kitchen team responsible for supporting the head chef or cook in food preparation and ensuring the smooth operation of the kitchen. This role plays a vital part in maintaining the quality and efficiency of a professional kitchen.',
        'Kitchen Staff': 'Kitchen staff, also known as kitchen crew or kitchen team members, are essential to the daily operations of a restaurant, catering service, or other food service establishment. They play a crucial role in ensuring that the kitchen runs smoothly, food is prepared correctly, and safety and hygiene standards are maintained.',
        'Dining Staff': 'Dining staff, often referred to as waitstaff or servers, play a critical role in providing a positive dining experience for guests at restaurants, cafes, hotels, and other food service establishments. Their primary responsibilities revolve around customer service, ensuring that patrons have an enjoyable and memorable dining experience.',
        'Supervisor': 'A supervisor is a key position in various industries and organizations, responsible for overseeing and managing a team or a specific department to ensure that operations run smoothly, efficiently, and in accordance with company policies and goals.',
        'Food Server': 'A food services worker is a vital member of the team in various food service establishments, including restaurants, cafeterias, catering companies, and institutional settings. They are responsible for a range of tasks related to food preparation, service, and customer satisfaction.',
        'Event Manager': 'An event manager is a skilled professional responsible for planning, organizing, and executing a wide range of events, such as conferences, weddings, corporate meetings, trade shows, and social gatherings. Event managers ensure that every aspect of an event runs smoothly, from initial concept development to post-event evaluations. Their goal is to create memorable and successful experiences for clients and attendees.',
        'Purchaser': 'A purchaser, often referred to as a procurement specialist or buyer, is responsible for sourcing, selecting, and acquiring goods and services that an organization needs to operate efficiently. This role plays a crucial part in managing the supply chain, ensuring that the organization has access to quality products and services while optimizing costs.',
        'Stylist': 'A stylist is a creative and fashion-savvy professional responsible for providing fashion and image-related services to individuals, clients, or organizations. Stylists use their expertise to enhance personal style, create fashionable looks, and achieve specific aesthetic goals.',
        'Event Host': 'A DJ/Event Host is a versatile entertainment professional responsible for creating and managing the musical atmosphere and overall experience at various events, including weddings, parties, corporate gatherings, and nightlife venues. This role combines the skills of a DJ, who curates and plays music, with those of an event host, who engages with the audience and ensures the event runs smoothly.',
        'Clown': 'Clowns, mimes, and comedians are talented entertainers who specialize in providing laughter, amusement, and entertainment through various forms of physical comedy, mimicry, and humor. While each of these roles has its unique characteristics and performance styles, they all share the common goal of making people smile, laugh, and forget their worries.'
    };

    var jobQualifications = {
        'Catering Manager': ['Male or Female', 'Graduate of Bachelor’s Degree preferably in Business Administration, Advertising, Marketing, Mass Communication and other related course', 'At least 5 years working experience in sales', 'With leadership, auditing and reportorial skills'],
        'Florist': ['Formal training in floral design or a related field is preferred but not always required.', 'Creative flair and a passion for working with flowers.', 'Knowledge of flower varieties, botanical terminology, and care techniques.', 'Excellent artistic and design skills.', 'Strong customer service and interpersonal skills.', 'Attention to detail and the ability to work under pressure.', 'Physical stamina to stand for extended periods and perform repetitive tasks.', 'Time management and organizational abilities.', 'Basic business and accounting skills for managing orders and finances.'],
        'Marketing Staff': ['A bachelors degree in marketing, communications, business, or a related field is often preferred.', 'Strong written and verbal communication skills.', 'Proficiency in digital marketing tools and platforms, such as Google Analytics, social media management tools, and email marketing software.', 'Familiarity with search engine optimization (SEO) principles and practices.', 'Analytical mindset and the ability to interpret data and draw insights.', 'Creativity and the ability to generate engaging marketing content.', 'Organizational skills and attention to detail.', 'Adaptability to changing marketing trends and technologies.', 'Knowledge of marketing principles, consumer behavior, and branding strategies.'],
        'Cook': ['Male or Female', 'Culinary training or relevant experience in a professional kitchen.', 'Knowledge of various cooking techniques and cuisines.', 'Ability to work efficiently in a fast-paced environment.', 'Attention to detail and a passion for creating delicious dishes.', 'Physical stamina to stand for extended periods and lift heavy pots and pans.', 'Excellent communication and teamwork skills.', 'Flexibility in working hours, including evenings, weekends, and holidays.'],
        'Assistant Cook': ['Previous experience in a kitchen environment is often preferred but not always required.', 'Basic knowledge of cooking techniques and food safety practices.', 'Ability to work in a fast-paced environment and handle high-pressure situations.', 'Physical stamina to stand for extended periods, lift heavy pots and pans, and perform repetitive tasks.', 'Attention to detail and the ability to follow instructions precisely.', 'Strong teamwork and communication skills.', 'Flexibility in working hours, including evenings, weekends, and holidays.'],
        'Kitchen Staff': ['Previous experience in a kitchen environment is often preferred but not always required.', 'Basic knowledge of cooking techniques and food safety practices.', 'Ability to work in a fast-paced environment and handle high-pressure situations.', 'Physical stamina to stand for extended periods, lift heavy pots and pans, and perform repetitive tasks.', 'Attention to detail and the ability to follow instructions precisely.', 'Strong teamwork and communication skills.', 'Flexibility in working hours, including evenings, weekends, and holidays.'],
        'Dining Staff': ['Excellent interpersonal and communication skills.', 'Strong customer service orientation and a friendly demeanor.', 'Ability to multitask and work efficiently in a fast-paced environment.', 'Attention to detail and the ability to handle cash and payments accurately.', 'Familiarity with the menu and the ability to answer guest questions.', 'Physical stamina to stand, walk, and carry trays for extended periods.', 'Knowledge of proper serving etiquette and restaurant protocols.', 'Flexibility in working hours, including evenings, weekends, and holidays.'],
        'Supervisor': ['Proven leadership and supervisory experience.', 'Strong communication and interpersonal skills.', 'Problem-solving and decision-making abilities.', 'Knowledge of industry-specific regulations and best practices.', 'Proficiency in relevant software and tools.', 'Excellent organizational and time management skills.', 'Adaptability and the ability to work under pressure.', 'A bachelors degree in a relevant field may be preferred in some industries, but it is not always required.'],
        'Food Server': ['Excellent interpersonal and customer service skills.', 'Ability to work in a fast-paced environment and handle high-pressure situations.' ,'Basic knowledge of food preparation and cooking techniques.' ,'Attention to detail and the ability to follow instructions precisely.' ,'Physical stamina to stand for extended periods and perform repetitive tasks.' ,'Strong teamwork and communication skills.' ,'Flexibility in working hours, including evenings, weekends, and holidays.' ,'Prior experience in the food service industry may be preferred but is not always required for entry-level positions.'],
        'Event Manager': ['Bachelors degree in event management, hospitality, or a related field (preferred).', 'Proven experience in event planning and management.', 'Strong project management and organizational skills.', 'Excellent communication and negotiation skills.', 'Creative probolving abilities.', 'Attention to detail and ability to multitask.', 'Proficiency in event management software and tools.', 'Adaptability to work irregular hours, including evenings and weekends.', 'Customer service orientation and the ability to build and maintain client relationships.'],
        'Purchaser': ['A bachelors degree in business, supply chain management, or a related field is often preferred.', 'Proven experience in procurement, purchasing, or supply chain management.', 'Strong negotiation and communication skills.', 'Analytical mindset and the ability to assess supplier proposals and cost data.', 'Familiarity with procurement software and tools.', 'Attention to detail and the ability to manage multiple procurement projects simultaneously.', 'Knowledge of supply chain principles, logistics, and inventory management.', 'Proficiency in Microsoft Excel and other relevant software applications.', 'Ethical and compliance-oriented approach to procurement practices.'],
        'Stylist': ['Education or training in fashion, styling, or a related field is often preferred.', 'Strong knowledge of fashion trends, designers, and brands.', 'Excellent fashion sense and a creative eye for style.', 'Strong communication and interpersonal skills.', 'Ability to understand and cater to diverse client needs and preferences.', 'Organization and time management skills to plan and execute styling appointments.', 'Attention to detail and a commitment to delivering high quality styling services.', 'Knowledge of garment care and maintenance.Proficiency in using fashion-related software and tools for outfit planning and coordination.'],
        'Event Host': ['Proven experience as a DJ and event host or emcee.', 'Extensive knowledge of music genres and the ability to read the crowds preferences.', 'Proficiency in using DJ equipment and software for music mixing.', 'Excellent public speaking and communication skills.', 'Adaptability and the ability to handle unexpected situations or requests.', 'Strong interpersonal skills to engage with diverse audiences.', 'Attention to detail and a commitment to delivering a high quality entertainment experience.', 'Knowledge of sound and lighting systems (preferred).', 'Experience with event planning or coordination (preferred).'],
        'Clown': ['Training: While formal education is not required, many performers in these roles receive training in physical comedy, mime, or stand-up comedy through workshops, classes, or performance arts schools.' , 'Performance Skills: Exceptional physical comedy skills, mimetic abilities, or comedic timing and delivery, depending on the specialization.' , 'Creativity: A creative and imaginative mind to develop unique and entertaining routines.' , 'Adaptability: The ability to tailor performances to different audiences and venues.' , 'Confidence: Self confidence and stage presence are essential for all performers in these roles.' , 'Physical Stamina: Good physical health and stamina, as performances may involve strenuous physical activity.' , 'Sense of Humor: A great sense of humor and an understanding of what makes people laugh.' , 'Costume and Makeup Skills: For clowns, the ability to create and apply makeup and costume designs is important.' , 'Audience Engagement: Strong audience engagement skills and the ability to read and respond to audience reactions.']
        
    };

    // Set job description and qualifications based on the jobTitle
    var description = jobDescriptions[jobTitle];
    var qualifications = jobQualifications[jobTitle];

    modalContent.innerHTML = `
        <h4>Job Description</h4>
        <p>${description}</p>
        <h4>Qualifications</h4>
        <p>${qualifications.map(item => `- ${item}`).join("<br>")}</p>`;
}

// Function to close the job modal
function closeModal() {
    modal.style.display = "none";
}

// Close the modal if the user clicks outside of it
window.addEventListener("click", function(event) {
    if (event.target === modal) {
        closeModal();
    }
});